

image: node:latest

services:
cache:
  key:
    files:
      - package.json
  paths:
    - node_modules

stages:
  - build
  - test
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml

build:
  stage: build
  script:
    - npm install
    - npm run build --if-present

test:
  stage: test
  script:
    - npm run format
    - npm run lint
    - npm run markdownlint
    - npm test