version: '3.4'

services:
  intersection:
    image: moeidheidari/intersection:v1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: intersection
    restart: always
    ports:
      - 8077:${NODE_PORT}
    environment:
      - NODE_ENV=  ${NODE_ENV}
      - NODE_PORT= ${NODE_PORT}
      - DECIMAL_PLACES= ${DECIMAL_PLACES}