apiVersion: skaffold/v2beta26
kind: Config
build:
  local:
    useBuildkit: true
  artifacts:
  - image: registry.gitlab.com/moeidtopcoder/intersection-over-union:latest
deploy:
  helm:
    releases:
    - name: app
      chartPath: k8s
      wait: true
      useHelmSecrets: true
      valuesFiles:
      - ./k8s/values.yaml
      - ./k8s/secrets.yaml
      artifactOverrides:
        image: registry.gitlab.com/moeidtopcoder/intersection-over-union:latest
      imageStrategy:
        helm: {}

portForward:
 - resourceType: service
   resourceName: app
   port: 8080
   localPort: 8080
