apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: intersection
  name: intersection
  namespace: intersection
spec:
  ports:
  - name: "8077"
    port: 8077
    targetPort: 8077
  selector:
    io.kompose.service: intersection
status:
  loadBalancer: {}
